version: '3.7'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - './web:/app'
      - '/app/node_modules'
    expose:
      - 4200
    ports:
      - 4200:4200  
################################
#   Setup nginx load balancer
################################
  nginx:
    image: nginx:1.13 # this will use the latest version of 1.13.x
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    depends_on: 
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      